"""User Model

Revision ID: 1a3042b7c71d
Revises: 31c966ae070a
Create Date: 2023-05-10 14:54:29.780827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3042b7c71d'
down_revision = '31c966ae070a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cards', sa.Column('descriptions', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Cards', 'Descriptions', ['descriptions'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Cards', type_='foreignkey')
    op.drop_column('Cards', 'descriptions')
    # ### end Alembic commands ###
