"""User Model

Revision ID: 26b9a60b551e
Revises: 24cfbc8c0a13
Create Date: 2023-05-23 16:02:43.813092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b9a60b551e'
down_revision = '24cfbc8c0a13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('Users', 'user_id')
    op.drop_column('Users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'created_at')
    # ### end Alembic commands ###
