"""User Model

Revision ID: 31c966ae070a
Revises: 5c3700ba8e12
Create Date: 2023-05-10 14:47:36.952658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c966ae070a'
down_revision = '5c3700ba8e12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('love_description', sa.String(), nullable=True),
    sa.Column('work_description', sa.String(), nullable=True),
    sa.Column('issue_description', sa.String(), nullable=True),
    sa.Column('money_description', sa.String(), nullable=True),
    sa.Column('health_description', sa.String(), nullable=True),
    sa.Column('spirit_description', sa.String(), nullable=True),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['Cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Descriptions')
    # ### end Alembic commands ###
