"""User Model

Revision ID: 4974d5ae0917
Revises: e66fedd60ef1
Create Date: 2023-05-12 16:32:27.043699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4974d5ae0917'
down_revision = 'e66fedd60ef1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
