"""empty message

Revision ID: 5bbe2a230b42
Revises: 
Create Date: 2023-05-08 11:38:02.840531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbe2a230b42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Harness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harness_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(), nullable=True),
    sa.Column('card_url', sa.String(), nullable=True),
    sa.Column('card_description', sa.String(), nullable=True),
    sa.Column('harness_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['harness_id'], ['Harness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cards')
    op.drop_table('Harness')
    # ### end Alembic commands ###
