"""User Model

Revision ID: 6e8bdc583f4f
Revises: c0a64251cddf
Create Date: 2023-05-10 15:39:06.168589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8bdc583f4f'
down_revision = 'c0a64251cddf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cards', sa.Column('descriptions_id', sa.Integer(), nullable=True))
    op.drop_constraint('Cards_descriptions_fkey', 'Cards', type_='foreignkey')
    op.create_foreign_key(None, 'Cards', 'Descriptions', ['descriptions_id'], ['id'])
    op.drop_column('Cards', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cards', sa.Column('descriptions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Cards', type_='foreignkey')
    op.create_foreign_key('Cards_descriptions_fkey', 'Cards', 'Descriptions', ['descriptions'], ['id'])
    op.drop_column('Cards', 'descriptions_id')
    # ### end Alembic commands ###
