"""User Model

Revision ID: 75c239d55eea
Revises: 6e8bdc583f4f
Create Date: 2023-05-10 22:04:04.115568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c239d55eea'
down_revision = '6e8bdc583f4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
