"""empty message

Revision ID: 8035aa51be7d
Revises: 8a6abc86c17a
Create Date: 2023-05-08 11:58:09.694550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8035aa51be7d'
down_revision = '8a6abc86c17a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Harness')
    op.add_column('Cards', sa.Column('harness', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cards', 'harness')
    op.create_table('Harness',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Harness_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('harness_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Harness_pkey')
    )
    # ### end Alembic commands ###
