"""empty message

Revision ID: 8a6abc86c17a
Revises: 5bbe2a230b42
Create Date: 2023-05-08 11:57:07.103904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6abc86c17a'
down_revision = '5bbe2a230b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Cards_harness_id_fkey', 'Cards', type_='foreignkey')
    op.drop_column('Cards', 'harness_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cards', sa.Column('harness_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Cards_harness_id_fkey', 'Cards', 'Harness', ['harness_id'], ['id'])
    # ### end Alembic commands ###
