"""User Model

Revision ID: 9418676f9fab
Revises: 4974d5ae0917
Create Date: 2023-05-13 22:55:12.890265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9418676f9fab'
down_revision = '4974d5ae0917'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
