"""new 

Revision ID: b3291c59139c
Revises: 
Create Date: 2023-05-16 11:50:38.877720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3291c59139c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('user_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'user_id')
    op.drop_column('Users', 'username')
    op.drop_column('Users', 'last_name')
    # ### end Alembic commands ###
