"""User Model

Revision ID: c0a64251cddf
Revises: c1a2ecaaec30
Create Date: 2023-05-10 15:35:40.175214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a64251cddf'
down_revision = 'c1a2ecaaec30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
