"""User Model

Revision ID: c1a2ecaaec30
Revises: 1a3042b7c71d
Create Date: 2023-05-10 15:27:55.914891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a2ecaaec30'
down_revision = '1a3042b7c71d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Descriptions_card_fkey', 'Descriptions', type_='foreignkey')
    op.drop_column('Descriptions', 'card')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Descriptions', sa.Column('card', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Descriptions_card_fkey', 'Descriptions', 'Cards', ['card'], ['id'])
    # ### end Alembic commands ###
