"""empty message

Revision ID: dc10cbd402db
Revises: e10d334213e6
Create Date: 2023-05-08 13:03:44.158888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc10cbd402db'
down_revision = 'e10d334213e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cards', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cards', sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
