"""Images Model

Revision ID: dfcbae81ce08
Revises: 75c239d55eea
Create Date: 2023-05-11 15:54:07.956345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcbae81ce08'
down_revision = '75c239d55eea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('love_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Cards', sa.Column('img_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'Cards', 'Images', ['img_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Cards', type_='foreignkey')
    op.drop_column('Cards', 'img_id')
    op.drop_table('Images')
    # ### end Alembic commands ###
