"""empty message

Revision ID: e10d334213e6
Revises: 8035aa51be7d
Create Date: 2023-05-08 12:54:18.702248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10d334213e6'
down_revision = '8035aa51be7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cards', sa.Column('descriptions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cards', 'descriptions')
    # ### end Alembic commands ###
