"""User Model

Revision ID: e66fedd60ef1
Revises: dfcbae81ce08
Create Date: 2023-05-11 15:57:59.652210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66fedd60ef1'
down_revision = 'dfcbae81ce08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Images', sa.Column('images_url', sa.String(), nullable=True))
    op.drop_column('Images', 'love_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Images', sa.Column('love_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Images', 'images_url')
    # ### end Alembic commands ###
