"""User Model

Revision ID: eabd61d5a909
Revises: 2d9c93ac33b5
Create Date: 2023-05-15 18:09:06.179970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabd61d5a909'
down_revision = '2d9c93ac33b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
