"""User Model

Revision ID: ee4edf06c506
Revises: 03c9499f3789
Create Date: 2023-05-10 13:14:57.729740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4edf06c506'
down_revision = '03c9499f3789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'card_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('card_url', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
